-- ================================================================
-- Vote.ai - Database Setup Script
-- Azure Database for PostgreSQL
-- ================================================================

-- Enable required extensions
-- ================================================================

-- UUID generation support
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Vector extension for AI embeddings (pgvector)
CREATE EXTENSION IF NOT EXISTS vector;


-- Create Tables
-- ================================================================

-- 1. Users Table
-- Stores user authentication and profile information
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'ambassador' CHECK (role IN ('ambassador', 'manager')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast email lookup during login
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);


-- 2. Suggestions Table
-- Stores ambassador suggestions/ideas with AI embeddings
CREATE TABLE IF NOT EXISTS suggestions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    
    -- AI embedding vector (1536 dimensions for OpenAI text-embedding-3-small)
    embedding vector(1536),
    
    -- Vote counter (indexed for fast sorting)
    vote_count INTEGER DEFAULT 0,
    
    -- Status workflow
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'implemented')),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Critical Index: Makes sorting by vote_count instant even with 100k+ rows
CREATE INDEX IF NOT EXISTS idx_suggestions_vote_count ON suggestions(vote_count DESC);

-- Index for vector similarity search (cosine distance)
CREATE INDEX IF NOT EXISTS idx_suggestions_embedding ON suggestions 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);


-- 3. Votes Table
-- Tracks which users voted on which suggestions (prevents duplicate voting)
CREATE TABLE IF NOT EXISTS votes (
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    suggestion_id UUID REFERENCES suggestions(id) ON DELETE CASCADE,
    voted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Composite primary key ensures one vote per user per suggestion
    PRIMARY KEY (user_id, suggestion_id)
);

-- Index for fast lookup of user's votes
CREATE INDEX IF NOT EXISTS idx_votes_user_id ON votes(user_id);

-- Index for fast lookup of suggestion's votes
CREATE INDEX IF NOT EXISTS idx_votes_suggestion_id ON votes(suggestion_id);


-- Sample Data (Optional - for testing)
-- ================================================================

-- Insert a test user
INSERT INTO users (email, full_name, password_hash, role)
VALUES (
    'test@example.com',
    'Test Ambassador',
    -- Password: 'test123' (hashed with bcrypt)
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyJSv.fOPMYS',
    'ambassador'
) ON CONFLICT (email) DO NOTHING;


-- Insert a sample suggestion
-- Note: In production, embeddings are generated by the backend
INSERT INTO suggestions (title, description, vote_count, status)
VALUES (
    'Improve Azure Student Credits',
    'We need better Azure credit limits for ML and AI projects',
    5,
    'pending'
) ON CONFLICT DO NOTHING;


-- Verify Setup
-- ================================================================

-- Check if extensions are enabled
SELECT 
    extname AS extension_name,
    extversion AS version
FROM pg_extension
WHERE extname IN ('uuid-ossp', 'vector');

-- Check tables
SELECT 
    table_name,
    pg_size_pretty(pg_total_relation_size(quote_ident(table_name))) AS size
FROM information_schema.tables
WHERE table_schema = 'public'
AND table_name IN ('users', 'suggestions', 'votes')
ORDER BY table_name;

-- Check indexes
SELECT 
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'public'
AND tablename IN ('users', 'suggestions', 'votes')
ORDER BY tablename, indexname;


-- ================================================================
-- Performance Notes (Senior Engineer Checklist)
-- ================================================================
--
-- 1. Vote Count Index (idx_suggestions_vote_count DESC):
--    - Makes ORDER BY vote_count DESC instant
--    - Critical for the "Top to Bottom" ranking feature
--
-- 2. Vector Index (idx_suggestions_embedding):
--    - Uses IVFFlat algorithm for fast similarity search
--    - lists = 100 is good for up to 100k suggestions
--    - Adjust lists value as data grows (rule: sqrt(rows))
--
-- 3. Composite Primary Key (votes table):
--    - Database-level enforcement of "one vote per user per suggestion"
--    - More reliable than application-level checks
--
-- 4. ON DELETE CASCADE (votes table):
--    - Automatically removes votes when user/suggestion is deleted
--    - Maintains referential integrity
--
-- 5. TIMESTAMP WITH TIME ZONE:
--    - Stores UTC time, handles timezones correctly
--    - Essential for global applications
--
-- ================================================================
